package com.smansara.tugasque.utils

object ListSelectors {

    val listKelas = listOf(
            "X-MIPA.1", "X-MIPA.2", "X-MIPA.3", "X-MIPA.4", "X-MIPA.5", "X-MIPA.6", "X-IPS.1", "X-IPS.2", "X-IPS.3", "X-IPS.4", "X-BB",
            "XI-MIPA.1", "XI-MIPA.2", "XI-MIPA.3", "XI-MIPA.4", "XI-MIPA.5", "XI-MIPA.6", "XI-IPS.1", "XI-IPS.2", "XI-IPS.3", "XI-IPS.4", "XI-BB",
            "XII-MIPA.1", "XII-MIPA.2", "XII-MIPA.3", "XII-MIPA.4", "XII-MIPA.5", "XII-MIPA.6", "XII-IPS.1", "XII-IPS.2", "XII-IPS.3", "XII-IPS.4", "XII-BB"
    )

    val listJenis = listOf("Tugas Rumah", "Tugas Sekolah", "Tugas Proyek", "Tugas Praktek")

    val listAdmin = listOf("Kepala Sekolah", "Guru", "Siswa")

    val listGuru = listOf(
    "A1   Drs. Nur Kholiq, M.Pd.",
    "A2   Trini Hastari, M.Pd.K.",
    "A3   Sufiati, S.Ag.",
    "A4   Drs. Hidayad, M.S.I.",
    "A5   Tarsisius Adi Prasetya, S.Pd.",
    "A6   Yusuf Nur Efendi, S.Pd.I.",
    "A7   Istini, S.Ag.",
    "B1   Drs. Bambang Sukrohadi",
    "B2   Nur Rohmad, S.Pd.",
    "B3   Sri Endah Lestari, S.Pd.",
    "B4   Alinda, S.Pd.",
    "C1   Udik Agus Dwi Wahyudi, M.Pd.",
    "C2   Anisah Achadiyah, S.Pd.",
    "C3   Suharyono, S.Pd.",
    "C4   Asih Welasati, S.Pd.",
    "C5   Zaenal Arief, S.Pd.",
    "C6   Bety Diana Sari, S.Pd.",
    "D1   Sunarti Sri Widyastuti, S.Pd.",
    "D2   Vika Fitrianasari, S.Pd., M.Si.",
    "D3   Eko Nurcahyaningsih, S.Pd.",
    "D4   Noor Saidah, S.Ag., M.Pd.",
    "E1   Haryono, S.Pd.",
    "E2   Soepartono, M.Pd.",
    "E3   Wahyoe Sugiarto, S.Si., M.Pd.",
    "E4   Rahma Addiena, S.Pd.",
    "E5   Muthiah Rakhmawati, S.Pd.",
    "E6   Khoirul Hadi, S.Pd.",
    "E7   Gilang Wisnu Adi, S.Pd.",
    "E8   Nuzulia Zahrotun Nisa, S.Pd.",
    "F1   Hariyanto, M.Pd.",
    "F2   Farida Fatkhiyati, S.Pd.",
    "F3   Masrini, S.Si.",
    "G1   Joko Dwi Murwono, S.Pd.",
    "G2   Sulistiyanti, S.Pd.",
    "G3   Edy Purwaka, S.Pd.",
    "H1   Ida Widiyastuti, M.Pd.",
    "H2   Any Noorhayati, S.Pd.",
    "H3   Maria Yekiana Mulyahati, M.Pd.",
    "H4   Rismawati, S.Pd.",
    "I1   Dra. Puji Rahayu, M.Pd.",
    "I2   Drs. Busri Ismail",
    "I3   Dra. Inayah Mutamaryati",
    "I4   Riski Rian Azan, S.Pd.",
    "J1   M. Cahyo Prihartono, S.Pd.",
    "J2   Qomarudin, M.Pd.",
    "K1   Dewi Safitri, S.Pd.",
    "K2   Desye Eistetiyanti, S.Pd.",
    "K3   Dwik Setyawan, S.Pd.",
    "L1   Eka Aries Setyaningsih, S.Sos., M.Pd.",
    "L2   Isna Yuliafatmah, S.Pd.",
    "M1   Drs. Bambang Sugiyanto",
    "M2   Makrus, S.Sn.",
    "M3   Anggoro Kristanto, S.Pd.",
    "N1   Drs. Cahyo Purwanto",
    "N2   Noor Efendy, S.Pd.",
    "N3   Muhammad Hanibal, S.Pd.",
    "N4   M. Affan Firdaus Nur, S.Pd.",
    "P1   Esti Hargorini, S.Pd.",
    "P2   Yusmanto, S.Pd.",
    "Q1   Abdul Haris, S.Pd.",
    "Q2   Retno Suryandari, S.S.",
    "R1   M. Elfin Noor, S.Kom., M.Pd.",
    "R2   Ninok Eyiz Sumianingrum, S.Kom., M.Pd.",
    "R3   Lilin Okta Melyanti, S.Kom.",
    "R4   Didik Setyoko, S.Kom.",
    "S1   Dra. Sri Sulistyowati",
    "S2   Dra. Nur Rakhmah",
    "S3   Emi Indriasari, S.Pd.",
    "S4   Muhammad Chotibul Umam, S.Pd.",
    "S5   Nur Fajriyah Sulistyoningsih, S.Pd."
    )

    val listMapel = listOf(
        "Pendidikan Agama dan Budi Pekerti",
        "Pendidikan Pancasila dan Kewarganegaraan",
        "Bahasa Indonesia",
        "Matematika",
        "Sejarah Indonesia",
        "Bahasa Inggris",
        "Seni Budaya",
        "Pendidikan Jasmani, Olah Raga dan Kesehatan",
        "Prakarya dan Kewirausahaan",
        "Bahasa Jawa",
        "Matematika (Peminatan)",
        "Biologi",
        "Fisika",
        "Kimia",
        "Geografi",
        "Sejarah (Peminatan)",
        "Sosiologi",
        "Ekonomi",
        "Bahasa dan Sastra Indonesia",
        "Bahasa dan Sastra Inggris",
        "Bahasa dan Sastra Perancis",
        "Antropologi",
        "Bimbingan dan Konseling",
        "TIK"
    )

}
